# Generated by Django 3.2.5 on 2021-07-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=500, null=True)),
                ('q2', models.CharField(blank=True, max_length=500, null=True)),
                ('q3', models.CharField(blank=True, max_length=500, null=True)),
                ('q4', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobtype', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remotly', 'Remotly')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('benefits', models.TextField(max_length=1000)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('experience', models.IntegerField(default=1)),
                ('job_img', models.ImageField(upload_to='photos')),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.categoty')),
                ('qualification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.qualification')),
            ],
        ),
    ]
