# Generated by Django 3.2.5 on 2021-07-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_apply_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='coveletter',
            new_name='coverletter',
        ),
    ]
