# Generated by Django 3.2.5 on 2021-07-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_apply_job_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='job',
        ),
    ]
