# Generated by Django 3.2.5 on 2021-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_job_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
