# Generated by Django 3.2.5 on 2021-07-28 16:00

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_job_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(validators=[job.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('', 'Job Type  '), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remotly', 'Remotly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(validators=[job.models.validate_positive]),
        ),
    ]
