# Generated by Django 3.2.5 on 2021-07-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210728_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categoty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.categoty'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('', 'Job Type'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remotly', 'Remotly')], max_length=100),
        ),
    ]
