# Generated by Django 3.2.5 on 2021-07-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_categoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categoty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.categoty'),
        ),
    ]
